## 7.1 Introduction

## 7.2 Creating arrays from existing Data

In [1]:

import numpy as np


In [2]:
numbers = np.array([2, 3, 5, 7, 11])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([ 2,  3,  5,  7, 11])

### Multidimensional Arguments

In [5]:
np.array([[1, 2, 3], [4, 6, 7]])

array([[1, 2, 3],
       [4, 6, 7]])

In [6]:

#Ndarray from comprehension list

np.array([item for item in range(2, 21) if item%2 == 0])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
np.array([item for item in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:

#2-5 Ndarray

np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

## 7.3 array Attributes

In [9]:

integers = np.array([[1, 2, 3], [4, 5, 6]])
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:

floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [11]:

#Determine the type

integers.dtype

dtype('int32')

In [12]:
floats.dtype

dtype('float64')

In [13]:

#Determine the dimension

integers.ndim

2

In [14]:
floats.ndim

1

In [22]:
integers.shape

(2, 3)

In [23]:
floats.shape

(5,)

In [24]:

#Number of elements and element size

integers.size

6

In [25]:
integers.itemsize #It contains 8 bytes

8

In [26]:
floats.size

5

In [27]:
floats.itemsize #It contains 8 bytes

8

In [28]:

# Iterating Through a Multidimensional array’s Elements

for row in integers:
    for column in row:
        print(column, end='  ')
    print()

1  2  3  
4  5  6  


In [15]:

for i in integers.flat: #Investigar
    print(i, end=' ')


1 2 3 4 5 6 

In [16]:

for i in floats.flat:
    print(i, end='  ')

0.0  0.1  0.2  0.3  0.4  

In [17]:

e = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])


In [36]:
e.ndim

2

In [37]:
e.shape

(2, 5)

## 7.4 Filling arrays with Specific Values

#### NumPy provides functions zeros, ones and full for creating arrays containing 0s, 1s or a specified value, respectively. By default, zeros and ones create arrays containing float64 values.

In [38]:

import numpy as np

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:

np.ones((2, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:

np.full((2, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

## 7.5 Creating arrays from Ranges

In [43]:

import numpy as np

np.arange(5)


array([0, 1, 2, 3, 4])

In [44]:

np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [56]:

np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [ ]:

'''Though you can create arrays by passing ranges as arguments, always use arange as it’s optimized for arrays.'''


In [61]:

#Creating Floating-Point Ranges with linspace

np.linspace(0.0, 1.0, num=5) #50 Spaces by default

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [69]:

#Reshaping an array

#You also can create an array from a range of elements, 
#then use array method reshape to transform the one-dimensional array into a multidimensional array.

np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [73]:

#Displaying Large arrays

np.arange(1, 10001).reshape(4, 2500)


array([[    1,     2,     3, ...,  2498,  2499,  2500],
       [ 2501,  2502,  2503, ...,  4998,  4999,  5000],
       [ 5001,  5002,  5003, ...,  7498,  7499,  7500],
       [ 7501,  7502,  7503, ...,  9998,  9999, 10000]])

In [74]:
np.arange(1, 10001).reshape(10, 1000)

array([[    1,     2,     3, ...,   998,   999,  1000],
       [ 1001,  1002,  1003, ...,  1998,  1999,  2000],
       [ 2001,  2002,  2003, ...,  2998,  2999,  3000],
       ...,
       [ 7001,  7002,  7003, ...,  7998,  7999,  8000],
       [ 8001,  8002,  8003, ...,  8998,  8999,  9000],
       [ 9001,  9002,  9003, ...,  9998,  9999, 10000]])

In [75]:

np.arange(2, 41, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

## 7.6 List vs. array Performance: Introducing %timeit

In [76]:

#Timing the Creation of a List Containing Results of 6,000,000 Die Rolls

import random

%timeit rolls_list = [random.randrange(1, 7) for item in range(0, 6000000)]

5.73 s ± 104 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [77]:

import numpy as np

%timeit rolls_array = np.random.randint(1, 7, 6000000) 

68.3 ms ± 2.88 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [78]:

%timeit rolls_array = np.random.randint(1, 7, 60_000_000)


910 ms ± 39.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [79]:
%timeit rolls_array = np.random.randint(1, 7, 60_000_000)

871 ms ± 37.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [80]:

#Customizing the %timeit Iterations

%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

83.1 ms ± 3.75 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [83]:

%timeit sum([x for x in range(10_000_000)]) 


782 ms ± 2.14 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [84]:
%timeit np.arange(10_000_000).sum()

23.2 ms ± 1.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 7.7 array Operators

In [99]:

# Arithmetic Operations with arrays and Individual Numeric Values

numbers = np.arange(1, 6)

numbers 

array([1, 2, 3, 4, 5])

In [100]:

numbers * 2


array([ 2,  4,  6,  8, 10])

In [101]:

numbers ** 3


array([  1,   8,  27,  64, 125])

In [102]:
numbers

array([1, 2, 3, 4, 5])

In [103]:

numbers += 10

numbers

array([11, 12, 13, 14, 15])

In [104]:

numbers


array([11, 12, 13, 14, 15])

In [105]:

# Broadcasting


#### When one operand is a single value, called a scalar, NumPy performs the element- wise calculations as if the scalar were an array of the same shape as the other operand, but with the scalar value in all its elements. This is called broadcasting.

In [106]:

# Arithmetic Operations Between arrays


numbers2 = np.linspace(1.1, 5.5, 5)
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [107]:

numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [108]:

#Comparing Arrays

numbers

array([11, 12, 13, 14, 15])

In [109]:
numbers >= 13

array([False, False,  True,  True,  True])

In [110]:

numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [111]:


numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [112]:

numbers == numbers2

array([False, False, False, False, False])

In [113]:

numbers == numbers

array([ True,  True,  True,  True,  True])

In [114]:


np.arange(1, 6)**2

array([ 1,  4,  9, 16, 25])

## 7.8 NumPy Calculation Methods

In [117]:

grades = np.array([[87, 96, 70], [100, 87, 90],
                  [94, 77, 90], [100, 81, 82]])

grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [118]:

grades.sum()

1054

In [119]:
grades.min()

70

In [120]:
grades.max()

100

In [121]:
grades.mean()

87.83333333333333

In [122]:
grades.std()

8.792357792739987

In [123]:
grades.var()

77.30555555555556

In [124]:

#Calculations by Row or Column

grades.mean(axis=0) #Average of every column(Average of each exam)

array([95.25, 85.25, 83.  ])

In [125]:

grades.mean(axis=1) #Average of every roe(Average of each estudent, of all exams)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [126]:

import numpy as np

grades = np.random.randint(60, 101, 12).reshape(3, 4)
grades

array([[97, 64, 94, 87],
       [95, 75, 77, 84],
       [94, 75, 66, 65]])

In [127]:

#Average of all grades

grades.mean()

81.08333333333333

In [128]:

#Average of each column(Average of each exam)

grades.mean(axis=0)

array([95.33333333, 71.33333333, 79.        , 78.66666667])

In [129]:

#Average of each row(Average of each student's exam)

grades.mean(axis=1)

array([85.5 , 82.75, 75.  ])

## 7.9 Universal Functions

In [18]:

numbers = np.array([1, 4, 9, 16, 25, 36])

np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [19]:

numbers2 = np.arange(1, 7)*10

numbers2

array([10, 20, 30, 40, 50, 60])

In [20]:
%timeit np.add(numbers, numbers2)

296 ns ± 1.04 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [21]:
%timeit numbers + numbers2

281 ns ± 0.489 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [133]:

#Broadcasting with Universal Functions

np.multiply(numbers2, 5)


array([ 50, 100, 150, 200, 250, 300])

In [135]:

numbers3 = numbers2.reshape(2, 3)
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [136]:

numbers4 = np.array([2, 4, 6])

In [137]:
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

In [141]:

#Other Universal Functions

numbers = np.arange(1, 6)

np.power(numbers, 3)

array([  1,   8,  27,  64, 125])

array([1, 2, 3, 4])

## 7.10 Indexing and Slicing

In [22]:

#Indexing with Two-Dimensional arrays

grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [23]:

grades[0, 1] #Row 1, Column 1

96

In [24]:

grades[1]

array([100,  87,  90])

In [25]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [26]:
grades[[1, 3]] #Multiple non-sequential rows

array([[100,  87,  90],
       [100,  81,  82]])

In [27]:
grades[[0,2]]

array([[87, 96, 70],
       [94, 77, 90]])

In [149]:

grades[:, 0] #All rows and the column 0

array([ 87, 100,  94, 100])

In [150]:

grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [151]:

grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

In [29]:
example = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14,15]])
example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
example[1]

array([ 6,  7,  8,  9, 10])

In [32]:
example[[0,2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [34]:
example[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

## 7.11 Views: Shallow copies

In [41]:

numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [42]:
numbers2 = numbers.view()
numbers2

array([1, 2, 3, 4, 5])

In [43]:
numbers[1] *= 10
numbers

array([ 1, 20,  3,  4,  5])

In [44]:
numbers2

array([ 1, 20,  3,  4,  5])